import type { Metadata } from "next";
import { Anton, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/src/components/SmoothScroll";
import ParticlesBackground from "@/src/components/ParticlesBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const heroDisplay = Anton({
  variable: "--font-hero-display",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${heroDisplay.variable} antialiased relative`}
      >
        <div className="relative z-10">
          <SmoothScroll>{children}</SmoothScroll>
        </div>

        <ParticlesBackground />

        {/* Emerald global shadow/glow overlay (above content so backgrounds don't cover it) */}
        <div aria-hidden className="pointer-events-none fixed inset-0 z-20 mix-blend-screen">
          {/* Soft bottom fade */}
          <div
            className="absolute left-1/2 -translate-x-1/2 bottom-[-10vh] w-[180vw] h-[55vh] rounded-full bg-gradient-to-t from-emerald-500/25 via-emerald-500/10 to-transparent"
            style={{
              WebkitMaskImage:
                "radial-gradient(ellipse 75% 95% at 50% 100%, #000 0%, #000 55%, transparent 72%)",
              maskImage:
                "radial-gradient(ellipse 75% 95% at 50% 100%, #000 0%, #000 55%, transparent 72%)",
            }}
          />
          {/* Big blurred bloom */}
          <div
            className="absolute left-1/2 -translate-x-1/2 bottom-[-36vh] w-[200vw] h-[85vh] rounded-full bg-emerald-500/25 blur-3xl"
            style={{
              // Semi-ovalo: más fuerte al centro, cae hacia los lados
              WebkitMaskImage:
                "radial-gradient(ellipse 75% 95% at 50% 100%, #000 0%, #000 55%, transparent 92%)",
              maskImage:
                "radial-gradient(ellipse 75% 95% at 50% 100%, #000 0%, #000 55%, transparent 92%)",
            }}
          />
        </div>
      </body>
    </html>
  );
}
